networks:
  shippros_net:
    driver: bridge

services:
  redis:
    image: redis:7-alpine
    container_name: shippros-redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - shippros_net

  api:
#    image: softvence/shippros-backend:latest
    build: .
    container_name: shippros_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    restart: always
    depends_on:
      - redis
    command: >
      sh -c "
        aerich init-db || true &&
        aerich migrate &&
        aerich upgrade || aerich upgrade --fake &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5

    networks:
      - shippros_net

volumes:
  db_data: